"""Retention, date of first and last interaction of user

Revision ID: facf5b6aba1f
Revises: 6faf6c87cbf1
Create Date: 2024-11-13 11:54:23.751319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'facf5b6aba1f'
down_revision: Union[str, None] = '6faf6c87cbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('retention', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('first_interaction', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_interaction', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_interaction')
    op.drop_column('users', 'first_interaction')
    op.drop_column('users', 'retention')
    # ### end Alembic commands ###
