"""New field add days in table promocode

Revision ID: 6faf6c87cbf1
Revises: 662ec0550b01
Create Date: 2024-11-12 12:22:28.776771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6faf6c87cbf1'
down_revision: Union[str, None] = '662ec0550b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('add_days', sa.Integer(), nullable=False))
    op.alter_column('promocode', 'add_balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promocode', 'add_balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('promocode', 'add_days')
    # ### end Alembic commands ###
