"""Added fields in table Persons for autopay logic

Revision ID: 662ec0550b01
Revises: 
Create Date: 2024-11-08 09:37:44.737359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662ec0550b01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_months', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscription_price', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('payment_method_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_method_id')
    op.drop_column('users', 'subscription_price')
    op.drop_column('users', 'subscription_months')
    # ### end Alembic commands ###
