"""server migration

Revision ID: 9449d7f40ef0
Revises: facf5b6aba1f
Create Date: 2025-01-30 20:36:05.792070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9449d7f40ef0'
down_revision: Union[str, None] = 'facf5b6aba1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal_requests', sa.Column('request_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('withdrawal_requests', sa.Column('payment_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_unique_constraint('withdrawal_requests_unique_constrain', 'withdrawal_requests', ['request_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('withdrawal_requests_unique_constrain', 'withdrawal_requests', type_='unique')
    op.drop_column('withdrawal_requests', 'payment_date')
    op.drop_column('withdrawal_requests', 'request_date')
    # ### end Alembic commands ###
